"""The four artifacts a real provisioner consumes.

This module is the heart of Option D. Given a validated submission it emits:
  1. iam-trust-policy.json   — who may assume the app's role (and only this app's runtime)
  2. iam-permissions.json    — least-privilege: one model, one S3 prefix, one secrets namespace
  3. deploy.yaml             — what the provisioner reads to stand up the service
  4. secrets-bootstrap.sh    — creates empty, named secret slots (never values)

Least-privilege is a platform invariant, not a knob: the scoping below is computed
from the slug/model and cannot be widened by tenant input. Tests assert this.
"""

from __future__ import annotations

import json

from app.catalog import model_by_id
from app.config import (
    APPS_BUCKET,
    AWS_ACCOUNT,
    AWS_REGION,
    HUMAN_IN_LOOP_BUDGET_USD,
    OBS_MCP_ENDPOINT,
    PLATFORM_SECRET_ROTATION_DAYS,
)
from app.manifest import _bare_repo
from app.schemas import Artifact, Submission


def trust_policy(sub: Submission) -> str:
    slug = sub.slug
    return json.dumps(
        {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Sid": "AppRunnerTaskAssume",
                    "Effect": "Allow",
                    "Principal": {"Service": "tasks.apprunner.amazonaws.com"},
                    "Action": "sts:AssumeRole",
                    "Condition": {
                        "StringEquals": {"aws:SourceAccount": AWS_ACCOUNT},
                        "ArnLike": {
                            "aws:SourceArn": f"arn:aws:apprunner:{AWS_REGION}:{AWS_ACCOUNT}:service/{slug}/*"
                        },
                    },
                }
            ],
        },
        indent=2,
    )


def permissions_policy(sub: Submission) -> str:
    slug = sub.slug
    model = model_by_id(sub.model_id)
    return json.dumps(
        {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Sid": "BedrockInvokeAllowlistedModelsOnly",
                    "Effect": "Allow",
                    "Action": ["bedrock:InvokeModel", "bedrock:InvokeModelWithResponseStream"],
                    "Resource": [f"arn:aws:bedrock:{AWS_REGION}::foundation-model/{model.model_id}"],
                },
                {
                    "Sid": "S3OwnPrefixOnly",
                    "Effect": "Allow",
                    "Action": ["s3:GetObject", "s3:PutObject", "s3:ListBucket"],
                    "Resource": [
                        f"arn:aws:s3:::{APPS_BUCKET}",
                        f"arn:aws:s3:::{APPS_BUCKET}/{slug}/*",
                    ],
                    "Condition": {"StringLike": {"s3:prefix": [f"{slug}/*"]}},
                },
                {
                    "Sid": "SecretsOwnNamespaceOnly",
                    "Effect": "Allow",
                    "Action": ["secretsmanager:GetSecretValue"],
                    "Resource": [
                        f"arn:aws:secretsmanager:{AWS_REGION}:{AWS_ACCOUNT}:secret:apps/{slug}/*"
                    ],
                },
                {
                    "Sid": "EmitTelemetry",
                    "Effect": "Allow",
                    "Action": ["cloudwatch:PutMetricData"],
                    "Resource": "*",
                    "Condition": {"StringEquals": {"cloudwatch:namespace": f"vibeapp/{slug}"}},
                },
            ],
        },
        indent=2,
    )


def deploy_config(sub: Submission) -> str:
    slug = sub.slug
    model = model_by_id(sub.model_id)
    lines = [
        "# deploy.yaml — generated by Vibeapp. Hand off to the provisioner as-is.",
        "apiVersion: vibeapp.alice.io/v1",
        "kind: AppDeployment",
        "metadata:",
        f"  name: {slug}",
        f"  owner: {sub.owner_email}",
        f"  team: {sub.team}",
        "source:",
        f"  repo: {_bare_repo(sub.repo_url)}",
        f"  ref: {sub.repo.ref}",
        f"  commit: {sub.repo.commit}",
        "runtime:",
        "  type: apprunner",
        "  container:",
        '    cpu: "1 vCPU"',
        '    memory: "2 GB"',
        f"    port: {sub.repo.port}",
        "    healthCheck: { path: /healthz, interval: 10 }",
        "  autoscaling: { min: 1, max: 3, maxConcurrency: 80 }",
        "iam:",
        "  trustPolicy: ./iam-trust-policy.json",
        "  permissions: ./iam-permissions.json",
        "env:",
        "  - { name: APP_ENV, value: production }",
        f"  - {{ name: MODEL_ID, value: {model.model_id} }}",
        f"  - {{ name: OBS_MCP_ENDPOINT, value: {OBS_MCP_ENDPOINT} }}",
        "guardrails:",
        f"  modelAllowlist: [{model.model_id}]",
        f"  monthlyBudgetUsd: {sub.budget}",
        "  piiScan: true",
        "  promptInjectionShield: true",
        f"  humanInLoop: {str(sub.budget >= HUMAN_IN_LOOP_BUDGET_USD).lower()}",
        "observability:",
        "  tracing: true",
        f"  attribution: {{ app: {slug}, owner: {sub.owner_email} }}",
    ]
    return "\n".join(lines)


def secrets_bootstrap(sub: Submission) -> str:
    slug = sub.slug
    keys = " ".join(s.key for s in sub.secrets)
    lines = [
        "#!/usr/bin/env bash",
        "# secrets-bootstrap.sh — creates the namespace + empty slots. Never the values.",
        "set -euo pipefail",
        f'NS="apps/{slug}"',
        "",
        f"for KEY in {keys}; do",
        "  aws secretsmanager create-secret \\",
        '    --name "$NS/$KEY" \\',
        '    --description "Managed by Vibeapp — set value via console or rotation job" \\',
        f"    --tags Key=app,Value={slug} Key=owner,Value={sub.owner_email} \\",
        f"    --region {AWS_REGION} 2>/dev/null \\",
        '  || echo "exists: $NS/$KEY (skipped)"',
        "done",
        "",
        f"# Rotation: ANTHROPIC_API_KEY is platform-managed and rotated centrally every {PLATFORM_SECRET_ROTATION_DAYS}d.",
    ]
    return "\n".join(lines)


def generate_artifacts(sub: Submission) -> list[Artifact]:
    return [
        Artifact(
            file="iam-trust-policy.json",
            lang="json",
            body=trust_policy(sub),
            label="IAM trust policy",
            note="Lets the app's runtime assume its own role — and nothing else's.",
        ),
        Artifact(
            file="iam-permissions.json",
            lang="json",
            body=permissions_policy(sub),
            label="Least-privilege permissions",
            note="Scoped to one model, one S3 prefix, one secrets namespace.",
        ),
        Artifact(
            file="deploy.yaml",
            lang="yaml",
            body=deploy_config(sub),
            label="Deployment config",
            note="What the provisioner reads to stand up the service.",
        ),
        Artifact(
            file="secrets-bootstrap.sh",
            lang="bash",
            body=secrets_bootstrap(sub),
            label="Secrets bootstrap",
            note="Creates empty, named slots. Values are set out-of-band.",
        ),
    ]
